name: Push to Lambda
on: [push]
jobs:
  PushToLambda:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
      - name: Poetry Install
        uses: Gr1N/setup-poetry@v7
      - name: Zip Dependencies
        run: bash .github/zip_dependencies.sh
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::826647375394:role/GitHubWorkflow_UpdateItemGeneratorLambdaFunction
          aws-region: us-east-1
      - name: Push to AWS Lambda
        run: aws lambda update-function-code --function-name item_generator --zip-file fileb://item_generator.zip
